version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: always
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root_secret
        ports:
            - "3309:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_network

volumes:
    mysql_data:

networks:
    laravel_network:
